### ISSUE TITLE
微信检测第三方客户端的问题

### ISSUE THREAD

**Issue by FantasticSkyBaby** [arlins/WeChatHookSDK#1]
如题，现在双开，多开自定义的微信会被检测出来，楼主对方面有研究吗

**Comment by arlins** [comment]
微信完全具备客户端篡改检测能力，如果你是自己重签，那比较困难。多开可选择下载pp助手提供的多开版本，这是成本最低的方式

**Comment by FantasticSkyBaby** [comment]
pp助手多开的原理是什么呢，为什么不会被检测

**Comment by arlins** [comment]
原理还是用pp助手的证书重签，但区别在于pp助手能选择稳定一些的版本重签。或者你换个角度想，如果pp助手官方推出的多开微信客户端存在问题，那么不会开放出来给用户下载使用

**Comment by FantasticSkyBaby** [comment]
请问你的红包设置里:主号IP地址 是做什么的 防检测的吗

**Comment by arlins** [comment]
主号和小号之间的TCP通信通道

**Comment by ruochen1989** [comment]
软件中的授权是什么意思？楼主出授权码吗？

**Comment by arlins** [comment]
授权码功能无用，可自己做精简

**Comment by ruochen1989** [comment]
楼主，你好，对于你自己封装的这个sdk，可否提供更加详细的使用说明呢？谢谢

**Comment by ruochen1989** [comment]
按照wiki设置，小号发红包后，主号日志提示自动抢包关闭，但是明明已经打开了，这是为什么呢？

**Comment by arlins** [comment]
开源的目的是为了学习而不是使用，跑起来以后如果有问题直接看源码吧，代码都在手上了
